# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
group: travis_latest
os: linux
dist: focal

# Travis allows these packages, additions can be requested
#   https://github.com/travis-ci/apt-package-safelist
addons:
  apt:
    packages: &common_packages
      - gfortran
      - libgfortran5
      - libatlas-base-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

# Disable clone depth
git:
  depth: false

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  include:
    - python: "3.8"
      os: linux
      arch: ppc64le
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       # - NPY_USE_BLAS_ILP64=1   # the openblas build fails
       - ATLAS=None
       # VSX4 still not supported by ubuntu/gcc-11
       - EXPECT_CPU_FEATURES="VSX VSX2 VSX3"

    - python: "3.8"
      os: linux
      arch: s390x
      # fixes VX assembler ambiguous errors
      # due to compiler incompatibility
      install: sudo apt update && sudo apt -y --only-upgrade install binutils
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - NPY_USE_BLAS_ILP64=1
       - ATLAS=None
       - EXPECT_CPU_FEATURES="VX VXE VXE2"

before_install:
  - ./tools/travis-before-install.sh

script:
  - ./tools/travis-test.sh
